server:
    port: 8081
    servlet:
      context-path: /client
    session:
      cookie:
        name: CLIENTSESSION
spring:
  security:
    oauth2:
      client:
        registration:
          custom:
            clientId: demo-client
            client-secret: secret
            client-name: SSO Client
            scope: user_info
            provider: custom
            redirect-uri-template: http://localhost:8081/client/login/oauth2/code/
            client-authentication-method: basic
            authorization-grant-type: authorization_code
            accessTokenUri: http://localhost:8080/server/oauth/token
        provider:
          custom:
            token-uri: http://localhost:8080/server/oauth/token
            authorization-uri: http://localhost:8080/server/oauth/authorize
            user-info-uri: http://localhost:8080/server/session/me
            user-name-attribute: name
logging:
  pattern:
    #console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36}.%M\\(%line\\) - %msg%n"
  level:
    org.springframework: INFO
    org.springframework.web.client: DEBUG
    org.springframework.security.oauth2: DEBUG

